/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 untitled.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[0, 2.629, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.653} />
    </group>
  )
}

useGLTF.preload('/untitled.gltf')
