/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../../public/model/cloth/cloth.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCloth(props) {
  const { nodes, materials } = useGLTF('/model/cloth/cloth.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 1.904, 0]} scale={2.396} />
    </group>
  )
}

useGLTF.preload('/model/cloth/cloth.gltf')
