/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ../../public/model/po/3d.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const path = '/model/po/3d.gltf'
export function Model(props) {
  const { nodes, materials } = useGLTF(path)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
    </group>
  )
}

useGLTF.preload(path)
