import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		// <html lang="en" className="bg-zinc-900 text-zinc-400">
		<html lang="en" className="">
			<body className={inter.className}>
				<div className="flex justify-between">
					<div className="flex px-3 py-2 gap-4">
						<Link href={"/timeline"}>Timeline</Link>
						<Link href={"/design"}>Design</Link>
						{/* <Link href="/order">Order</Link>
						<Link href="/sub">Sub</Link> */}
						{/* <Link href="/price">Price</Link>
						<Link href="/material">Material</Link>
						<Link href="/item">Item</Link> */}
					</div>
					<div className="px-3 py-2 font-semibold">
						<Link href="/">RUNSNAP</Link>
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
