/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 untitled.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function BModel(props) {
  const { nodes, materials } = useGLTF('/model/b/b.gltf')
  const texture = useTexture("/pic/pic2.jpeg")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 2.629, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={2.653}>

        <meshStandardMaterial map={texture} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/model/b/b.gltf')
