/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 box.gltf
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'

export function BoxModel(props) {
  const { nodes, materials } = useGLTF('/model/box/box.gltf')
  const texture = useTexture("/mode/pic2.jpeg")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 1.046, 0]}>
        <Decal map={texture} debug />
        {/* <meshStandardMaterial map={texture} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/model/box/box.gltf')
