/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 box.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function ModelBox2(props) {
  const path = '/model/box2/'
  // const { nodes, materials } = useGLTF(`${path}/box.gltf`)
  const { nodes, materials } = useGLTF("/model/box2//box.gltf")
  const texture = useTexture('/pic/pic2.jpeg')
  const teriansTexture = useTexture({
    aoMap: "/model/box2/untitled_ao.png",
    normalMap: "/model/box2/untitled_normal.png",
    // displacementMap: "/model/box2/untitled_curvature.png"
  })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 1.046, 0]}>

        <meshStandardMaterial map={texture}  {...teriansTexture}  />
      </mesh>
    </group>

  )
}

useGLTF.preload('/model/box2/box.gltf')
