/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 concrete_cat_statue_1k.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCat(props) {
  const { nodes, materials } = useGLTF('/model/cat/concrete_cat_statue_1k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.concrete_cat_statue.geometry} material={materials.concrete_cat_statue} />
    </group>
  )
}

useGLTF.preload('/model/cat/concrete_cat_statue_1k.gltf')
