/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 mat.gltf
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useAppContext } from '@/context/app/AppReducer';

export function ModelMat(props) {
  const {blob} = props
  const { nodes, materials } = useGLTF('/model/mat/mat.gltf')
  // const texture = useTexture("/model/mat/pic.png")
  const textureArtwork = useTexture(blob)

    return (<>
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 0.627, 0]}>
          <meshStandardMaterial map={textureArtwork}  />
        </mesh>
    </group>
    </>)



}

useGLTF.preload('/model/mat/mat.gltf')
