/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 4d.gltf
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'

export function ModelNew(props) {
  const { nodes, materials } = useGLTF('/model/new/4d.gltf')
  const t = useTexture({
    aoMap: "/model/new/untitled_ao.png",
    // displacementMap: "/model/new/untitled_curvature.png",
    normalMap: "/model/new/untitled_normal.png"
  })
  const texture = useTexture("/pic/pic2.jpeg")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material}>
        {/* <meshStandardMaterial map={texture} {...t}   /> */}
        <Decal debug position={[0,2,0]} scale={3}>

          <meshStandardMaterial map={texture} {...t} />
        </Decal>
      </mesh>
    </group>
  )
}

useGLTF.preload('/model/new/4d.gltf')
