/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Shirt.gltf
*/

import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
import { useGLTF, useTexture } from '@react-three/drei'

export function ModelShirt(props) {
  // const {blob} = props
  const { nodes, materials } = useGLTF('/model/shirt/Shirt.gltf')

  // const textureArtwork = useTexture(blob)
  // console.log(textureArtwork);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.RetopoFlow.geometry} material={materials['Material.002']}>
          {/* <meshStandardMaterial map={textureArtwork}  /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/model/shirt/Shirt.gltf')
