/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 t-shirt2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTeeShirt(props) {
  const { nodes, materials } = useGLTF('/model/tee_shirt/t-shirt2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shirt.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/model/tee_shirt/t-shirt2.gltf')
